# Generated by Django 5.1.1 on 2024-10-17 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='availability',
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('yes', '〇'), ('maybe', '△'), ('no', '×')], max_length=10)),
                ('event_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.eventdate')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='scheduler.participant')),
            ],
        ),
    ]
