# Generated by Django 5.1.1 on 2024-10-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_participant_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdate',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
